# Generated by Django 5.0.4 on 2024-04-23 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='avaatar',
            new_name='avatar',
        ),
    ]
