# Generated by Django 5.0.4 on 2024-04-24 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_lesson_course'),
        ('users', '0003_rename_avaatar_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payed_lesson',
            field=models.ManyToManyField(to='materials.lesson', verbose_name='Оплаченный урок'),
        ),
    ]
