# Generated by Django 5.0.4 on 2024-04-25 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_lesson_course'),
        ('users', '0004_alter_payment_payed_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payed_course',
            field=models.ManyToManyField(to='materials.course', verbose_name='Оплаченный курс'),
        ),
    ]
