# Generated by Django 5.0.4 on 2024-05-08 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_payment_payed_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cash', 'Наличный'), ('transfer', 'Перевод')], max_length=50, verbose_name='Способ оплаты'),
        ),
    ]
